name: Build & Upload bleeding edge version

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (build only, skip upload)'
        required: false
        type: boolean
        default: false

env:
  ProjectName: SnoringPony
  PackagesVersion: 1.2.10

jobs:
  linux:
    uses: ./.github/workflows/sub-build-osx.yml
  osx:
    uses: ./.github/workflows/sub-build-linux.yml
  windows:
    uses: ./.github/workflows/sub-build-win.yml
    secrets:
      DEPDIRURL: ${{ secrets.DEPDIRURL }}

  uploads:
    name: Uploads on S3
    if: ${{ github.event.inputs.dry_run == 'false' }}
    needs: [windows, osx, linux]
    runs-on: ubuntu-latest
    steps:
      - name: Install s3cmd
        run: sudo apt-get install -y s3cmd

      - name: Install the Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          version: v2.37.0

      - name: Get win64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: win-x64

      - name: Get osx-intel artifacts
        uses: actions/download-artifact@v4
        with:
          name: osx-x86_64

      - name: Get osx-silicon artifacts
        uses: actions/download-artifact@v4
        with:
          name: osx-arm64

      - name: Get linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux

      - name: Upload to Scaleway Object Storage
        run: |
          scw object config get type=s3cmd > /home/runner/.s3cfg
          s3cmd --no-mime-magic --guess-mime-type sync ./* s3://${{ secrets.SCW_DEV_S3 }}/
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_DEV_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_DEV_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEV_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEV_DEFAULT_ORGANIZATION_ID }}
