name: Build linux
on: [workflow_call]

env:
  ProjectName: SnoringPony

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set Suffix
        id: set_variables
        uses: ./.github/actions/set-suffix
        with:
          os: 'x64'

      - name: Installing dependencies
        id: install_deps
        #shell: bash {0} # Opt out of fail-fast behavior (necessary to ignore fetch errors)
        run: |
          sudo apt-get update
          echo "Installing JUCE lib dependencies and extra tools"
          sudo apt-get install -qyf libcurl3-gnutls libfreetype6-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev libxcomposite-dev mesa-common-dev libasound2-dev freeglut3-dev libcurl4-gnutls-dev libasound2-dev libjack-dev libbluetooth-dev libgtk-3-dev libwebkit2gtk-4.0-dev libsdl2-dev libfuse2 libfuse2 libusb-1.0-0-dev libhidapi-dev ladspa-sdk libssl-dev
          sudo apt-get install -qy curl

          cd ${{ github.workspace }}
          wget "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod a+x appimagetool-x86_64.AppImage

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/Builds/LinuxMakefile
          gcc --version
          make -j2 CONFIG=Release

      - name: Create AppImage
        id: create_package
        run: |
          mkdir -p ${{ env.ProjectName }}.AppDir/usr/bin/
          cp build/${{ env.ProjectName }} ${{ env.ProjectName }}.AppDir/usr/bin/

          PKGNAME=${{ env.ProjectName }}-linux-${{ steps.set_variables.outputs.suffix }}.AppImage
          echo "pkg-name=$PKGNAME" >> $GITHUB_OUTPUT
          ARCH=x86_64 $GITHUB_WORKSPACE/appimagetool-x86_64.AppImage --appimage-extract-and-run ${{ env.ProjectName }}.AppDir $PKGNAME
        working-directory: ./Builds/LinuxMakefile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./Builds/LinuxMakefile/${{ steps.create_package.outputs.pkg-name }}
