name: Build Windows

on:
  workflow_call:
    secrets:
      DEPDIRURL:
        required: true

env:
  ProjectName: SnoringPony

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    strategy:
      matrix:
        include:
        - arch: win-x64
          buildFolder: "VisualStudio2022_CI"
          installerName: install

        # - arch: win7-x64
        #   buildFolder: "VisualStudio2022_Win7CI"
        #   installerName: installWin7

      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set Variables
        id: set_variables
        uses: ./.github/actions/set-suffix
        with:
          os: ${{ matrix.arch }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Force 64-bit Linker
        shell: powershell
        run: |
          cmd.exe /c "call `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
          Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] }}

      - name: Build
        run:  msbuild "Builds/${{ matrix.buildFolder }}/${{ env.ProjectName }}.sln" /p:PreferredToolArchitecture=x64 /m /verbosity:normal /p:Configuration=${{ steps.set_variables.outputs.config }}

      - name: Create Package
        id: create_package
        shell: powershell
        run: |
          Set-Variable -Name "PKGNAME" -Value "${{ env.ProjectName }}-${{ steps.set_variables.outputs.suffix }}"
          Invoke-WebRequest "${{ secrets.DEPDIRURL }}${{ env.ProjectName }}-win-x64-${{ steps.set_variables.outputs.dep }}-dependencies.zip" -OutFile ./deps.zip
          7z e deps.zip -aoa
          &"C:/Program Files (x86)/Inno Setup 6/ISCC.exe" "${{ github.workspace }}/${{ matrix.installerName }}.iss" /O. /F$PKGNAME
          echo "pkg-name=$PKGNAME.exe" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "pdb-name=$PKGNAME.pdb" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        working-directory: ./Binaries/CI/App

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: ./Binaries/CI/App/${{ steps.create_package.outputs.pkg-name }}

      # - name: Rename PDB
      #   if: ${{ steps.set_variables.outputs.config == 'Release' && matrix.arch == 'win-x64' }}
      #   id: rename_pdb
      #   shell: powershell
      #   run: |
      #     Rename-Item -Path "./${{ env.ProjectName }}.pdb" -NewName "${{ steps.create_package.outputs.pdb-name }}"
      #   working-directory: ./Builds/${{ matrix.buildFolder }}/x64/${{ steps.set_variables.outputs.config }}/App

      # - name: Upload PDB
      #   if: ${{ steps.set_variables.outputs.config == 'Release' && matrix.arch == 'win-x64' }}
      #   uses: ./.github/actions/upload
      #   with:
      #     pkg-name: ./Builds/${{ matrix.buildFolder }}/x64/${{ steps.set_variables.outputs.config }}/App/${{ steps.create_package.outputs.pdb-name }}
      #     url: ${{ secrets.PDBUPLOADURL }}
      #     pass: ${{ secrets.UPLOADPASS }}
